### PR TITLE
Completed css-brochure-form exercise.

### PR DESCRIPTION
**Pull request by yahnbaron**
image

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Baron! The font size of the placeholders in each form control is a bit too large compared to the example. Additionally, the `input` and `select` elements have too little padding. Please revise and submit a new screenshot with your revision.

**Comment by yahnbaron** [comment]
Screenshot 2022-10-12 at 4 49 07 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Your form is now too narrow, the label for the `select` is breaking to two lines. Please make your form wider

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
